"""Default placeholder services for the yk-FERTA pipeline."""

from __future__ import annotations

from yk_ferta.schemas.clinical import CandidateCondition, PatientProfile, PhenotypeItem
from yk_ferta.schemas.evidence import CandidateReview, EvidenceItem, TraceableRecommendation


class PassthroughPhenotypeStandardizer:
    """Temporary adapter until the local phenotype agent is integrated."""

    def standardize(self, patient: PatientProfile) -> list[PhenotypeItem]:
        text = patient.narrative()
        if not text:
            return []
        return [
            PhenotypeItem(
                label="unstructured clinical narrative",
                source="passthrough",
                confidence=0.1,
                notes=text[:500],
            )
        ]


class StubEvidenceRetriever:
    """Deterministic retriever used for early integration and tests."""

    def retrieve(
        self,
        patient: PatientProfile,
        phenotypes: list[PhenotypeItem],
    ) -> list[EvidenceItem]:
        phenotype_labels = ", ".join(item.label for item in phenotypes) or "no phenotype extracted"
        return [
            EvidenceItem(
                source_id="local-guideline-placeholder",
                source_type="guideline",
                title="Placeholder fertility guidance",
                summary=(
                    "Early yk-FERTA workspace placeholder. Replace with real guideline, "
                    "literature, case-bank, and product evidence adapters."
                ),
                citation=f"Phenotype context: {phenotype_labels}",
            )
        ]


class HeuristicCandidateGenerator:
    """Simple deterministic candidate generator for pipeline scaffolding."""

    def generate(
        self,
        patient: PatientProfile,
        phenotypes: list[PhenotypeItem],
        evidence: list[EvidenceItem],
        top_k: int,
    ) -> list[CandidateCondition]:
        base_rationale = (
            "Placeholder candidate generated by the scaffolding pipeline. "
            "Replace with domain reasoning over phenotypes, evidence, and local models."
        )
        candidates = [
            CandidateCondition(
                name="Need domain-specific candidate engine",
                rank=1,
                score=0.2,
                rationale=base_rationale,
                supporting_phenotypes=[item.label for item in phenotypes[:5]],
            )
        ]
        return candidates[:top_k]


class SupportiveEvidenceVerifier:
    """Conservative placeholder verifier that keeps the pipeline structurally complete."""

    def verify(
        self,
        patient: PatientProfile,
        phenotypes: list[PhenotypeItem],
        evidence: list[EvidenceItem],
        candidates: list[CandidateCondition],
    ) -> list[CandidateReview]:
        evidence_ids = [item.source_id for item in evidence]
        return [
            CandidateReview(
                candidate_name=candidate.name,
                is_supported=bool(evidence),
                confidence=0.2 if evidence else 0.0,
                reasoning=(
                    "Placeholder verification only checks that at least one evidence item "
                    "exists. Replace with evidence-grounded candidate validation."
                ),
                evidence_ids=evidence_ids,
            )
            for candidate in candidates
        ]


class BasicTraceableOutputBuilder:
    """Assemble a structured physician-facing recommendation."""

    def build(
        self,
        patient: PatientProfile,
        phenotypes: list[PhenotypeItem],
        evidence: list[EvidenceItem],
        candidates: list[CandidateCondition],
        reviews: list[CandidateReview],
    ) -> TraceableRecommendation:
        supported = [review.candidate_name for review in reviews if review.is_supported]
        if supported:
            summary = f"Generated {len(candidates)} candidate(s); supported candidate(s): {', '.join(supported)}."
        else:
            summary = "Generated candidate scaffold, but no candidate has been robustly verified yet."

        return TraceableRecommendation(
            summary=summary,
            candidates=candidates,
            evidence=evidence,
            reviews=reviews,
            next_steps=[
                "Integrate the local phenotype generation agent into the phenotype standardization stage.",
                "Replace placeholder evidence retrieval with controlled knowledge and case retrieval adapters.",
                "Add domain-specific candidate ranking and evidence verification logic.",
            ],
            cautions=[
                "Current output is a scaffolding response and is not suitable for clinical use.",
            ],
        )
